apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: ce-writer
  namespace: default
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: ce-writer

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ce-writer
  labels:
    sql-inject: "true"
spec:
  template:
    spec:
      containers:
      - image: ko://github.com/vaikas/postgres/cmd/cewriter
        env:
        - name: DBNAME
          value: "cloudevents"
