apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ville-test
  labels:
    sql-inject: true
spec:
  template:
    spec:
      containers:
      - image: ko://github.com/vaikas/postgres/cmd

---

apiVersion: bindings.mattmoor.dev/v1alpha1
kind: SQLBinding
metadata:
  name: vaikas-binding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    # Either name or selector may be specified.
    selector:
      matchLabels:
        sql-inject: true

  secret:
    name: sql-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
stringData:
  # Replace this with appropriate values
  connectionstr: postgres://<username>:<password>@<ip>:<port>
