apiVersion: batch/v1
kind: Job
metadata:
  name: initdb-job
  labels:
    sql-inject: "true"
spec:
  template:
    metadata:
      labels:
        sql-inject: "true"
    spec:
      restartPolicy: Never
      containers:
      - name: initdb
        image: ko://github.com/vaikas/postgres/cmd/initdb
        
