apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: insertuser
  labels:
    sql-inject: "true"
spec:
  template:
    spec:
      containers:
      - image: ko://github.com/vaikas/postgres/cmd/insertuser
